# Generated by Django 5.2.1 on 2025-05-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(default='', max_length=255, verbose_name='岗位名称')),
                ('address', models.CharField(default='', max_length=255, verbose_name='城市')),
                ('type', models.CharField(default='', max_length=255, verbose_name='职业')),
                ('educational', models.CharField(default='', max_length=255, verbose_name='学历')),
                ('workExperience', models.CharField(default='', max_length=255, verbose_name='工作经验')),
                ('workTag', models.TextField(default='', max_length=10000, verbose_name='工作标签')),
                ('salary', models.CharField(default='', max_length=255, verbose_name='工资')),
                ('salaryMonth', models.CharField(default='', max_length=255, verbose_name='年终奖')),
                ('companyTags', models.TextField(default='', max_length=10000, verbose_name='福利')),
                ('hrWork', models.CharField(default='', max_length=255, verbose_name='hr职位')),
                ('hrName', models.CharField(default='', max_length=255, verbose_name='hr名字')),
                ('practice', models.BooleanField(default='', max_length=255, verbose_name='是否为实习岗位')),
                ('companyTitle', models.CharField(default='', max_length=255, verbose_name='公司名称')),
                ('companyAvatar', models.CharField(default='', max_length=255, verbose_name='公司logo')),
                ('companyNature', models.CharField(default='', max_length=255, verbose_name='公司性质')),
                ('companyStatus', models.CharField(default='', max_length=255, verbose_name='融资状态')),
                ('companyPeople', models.CharField(default='', max_length=255, verbose_name='公司规模')),
                ('detailUrl', models.TextField(default='', max_length=10000, verbose_name='详情链接')),
                ('companyUrl', models.TextField(default='', max_length=10000, verbose_name='公司链接')),
                ('dist', models.CharField(default='', max_length=255, verbose_name='行政区')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'db_jobInfo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('userName', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('educational', models.CharField(default='', max_length=255, verbose_name='学历')),
                ('workExperience', models.CharField(default='', max_length=255, verbose_name='工作经验')),
                ('address', models.CharField(default='', max_length=255, verbose_name='意向城市')),
                ('work', models.CharField(default='', max_length=255, verbose_name='意向工作')),
                ('avatar', models.FileField(default='avatar/defaultAvatar.jpg', upload_to='avatar', verbose_name='头像')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'db_user',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('searchTitle', models.CharField(default='', max_length=255, verbose_name='搜索词')),
                ('count', models.IntegerField(default=1, verbose_name='搜索次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'db_searchHistory',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('count', models.IntegerField(default=1, verbose_name='访问次数')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'db_history',
            },
        ),
    ]
